---
# defaults file for roles/kickstart
#
tftp_pkgs: tftp-server,syslinux,xinetd
tftp_pxe: 
 - /usr/share/syslinux/pxelinux.0 
 - /usr/share/syslinux/vesamenu.c32
 - /{{ web_root }}/{{ ansible_distribution }}/isolinux/initrd.img
 - /{{ web_root }}/{{ ansible_distribution }}/isolinux/vmlinuz

tftp_uefi:
 - /{{ web_root }}/{{ ansible_distribution }}/EFI/BOOT/BOOTX64.EFI
 - /{{ web_root }}/{{ ansible_distribution }}/EFI/BOOT/grubx64.efi

apache: httpd
reponame: localrepo

#Settable variables
#Remove the iso from the system? Override to "true" to keep.
keep_iso: true

#Keep local yum repo or delete it? Override to "true" to keep.
keep_repo: true

#Keep iso mounted? Override to "true" to keep.
keep_mnt: true

# Set to "true" to enable DHCP.
dhcp: true

# Default cleanup set to false
cleanup: false