---
- name: "Install pip"
  yum:
    name: python-pip
    state: present

- name: Install pip2pi
  pip:
    name: pip2pi

- name: "Download pip packages to the custom install repo"
  shell: "pip download -d {{ tfplenumoffline_dir }}/pip {{ item }}"
  with_items:
  - "{{ pip_downloads }}"

- name: create pip repo
  shell: "dir2pi {{ tfplenumoffline_dir }}/pip"
  