- name: Remove Repodata from {{ repo }}
  file:
    path: "{{ tfplenumoffline_dir }}/{{ repo }}/repodata"
    state: absent

- name: Validate if comps.xml exists in {{ repo }}
  stat:
    path: "{{ tfplenumoffline_dir }}/{{ repo }}/comps.xml"
  register: comps_result

- set_fact:
    createrepo_cmd: "createrepo -g  {{ tfplenumoffline_dir }}/{{ repo }}/comps.xml {{ tfplenumoffline_dir }}/{{ repo }} "
  when: comps_result.stat.exists

- set_fact:
    createrepo_cmd: "createrepo {{ tfplenumoffline_dir }}/{{ repo }}"
  when: comps_result.stat.exists == false

- name: "Create {{ repo }} repo"
  shell: "{{ createrepo_cmd }}"