---
- name: "Create directory for offline repos"
  file:
    path: "{{ tfplenumoffline_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
    setype: httpd_sys_content_t

- name: "Create tfplenum repo directory"
  file:  
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ TFPLENUM_REPO_DIR }}"
    - "{{ TFPLENUM_REPO_DIR }}/Packages"

- name: "Install bootstrap packages"
  yum:
    name: "{{ bootstrap_package_names }}"
    state: present

- name: Enable Firewalld Service
  service:
    name: "firewalld"
    state: started
    enabled: true
