---
- block:
  - name: Download Elasticdump
    npm:
      name: elasticdump
      path: /tmp

  - name: Pack node modules dir
    archive:
      path: "/tmp/node_modules"
      dest: "{{ tfplenumoffline_dir }}/elasticdump.tar.gz"
