---

- name: "Download all other direct download files into local repository, including dependencies"
  get_url:
    url: "{{ item }}" 
    dest: "{{ tfplenumoffline_dir }}/tfplenum/Packages"
  with_items:
    - "{{ direct_download_package_names }}"
  when: "'.rpm' in item"

- name: "Download all other direct download files into local repository, including dependencies"
  get_url:
    url: "{{ item }}" 
    dest: "{{ tfplenumoffline_dir }}"
  with_items:
    - "{{ direct_download_package_names }}"
  when: "'.rpm' not in item"