---

- name: Remove Repodata from {{ repo }}
  file:
    path: "{{ offline_dir }}/{{ repo }}/repodata"
    state: absent

- name: Validate if comps.xml exists in {{ repo }}
  stat:
    path: "{{ offline_dir }}/{{ repo }}/comps.xml"
  register: comps_result

- set_fact:
    createrepo_cmd: "createrepo -g  {{ offline_dir }}/{{ repo }}/comps.xml {{ offline_dir }}/{{ repo }} "
  when: comps_result.stat.exists

- set_fact:
    createrepo_cmd: "createrepo {{ offline_dir }}/{{ repo }}"
  when: comps_result.stat.exists == false

- name: "Create {{ repo }} repo"
  shell: "{{ createrepo_cmd }}"

...