#######################################################
################## Predownload Repos ##################
#######################################################
---

- name: Check if ran by bootstrap
  fail:
    msg: 'Clonerepos role must be run using bootstrap script'
  when: BOOTSTRAP == false

- name: Import tfplenum variables
  include_vars:
    file: "{{ group_vars_location }}"

- import_tasks: 00_httpd.yml
- import_tasks: 02_isos.yml
- import_tasks: 05_setup.yml
- import_tasks: 10_pip.yml
  tags: pip
- import_tasks: 11_elasticdump.yml  
  tags: elasticdump
- import_tasks: 15_direct.yml
  tags: direct
- import_tasks: 20_download_rpms.yml

...
