---
- name: Configure dns server
  block:    
    - name: Create /etc/hosts
      template:
        src: "hosts.j2"
        dest: "/etc/hosts"
        owner: root
        group: root
        mode: 0644
      register: dnsmasq_result
      notify: "Restart Network Services"
    
    - meta: flush_handlers

    - name: Install packages
      yum:
        name: "dnsmasq"
        state: latest

    - name: DNS Services
      service:
        name: "dnsmasq"
        state: started
        enabled: yes      

    - name: DNS Firewall
      firewalld:
        service: dns
        state: enabled
        immediate: yes
        permanent: yes     
      notify: "Restart Docker"   
  when: dnsmasq is defined and dnsmasq


